export const actionTypes = {
  GET_PICTURES: "GET_PICTURES",
  GET_DETAILS: "GET_DETAILS"
};

export const mutationTypes = {
  GET_PICTURES_SUCCESS: "GET_PICTURES_SUCCESS",
  GET_DETAILS_SUCCESS: "GET_DETAILS_SUCCESS"
};
